=== betairylia/Titanians/dist/data/resources-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "ResourceData": {
            "properties": {
                "color": {
                    "type": "string"
                },
                "env": {
                    "type": "boolean"
                },
                "initialMaxStacks": {
                    "type": "number"
                },
                "initialUMaxStacks": {
                    "type": "number"
                },
                "initialUTransferSpeed": {
                    "type": "number"
                },
                "regenBase": {
                    "type": "number"
                },
                "regenFactor": {
                    "type": "number"
                },
                "type": {
                    "$ref": "#/definitions/ResourceType"
                }
            },
            "type": "object"
        },
        "ResourceType": {
            "enum": [
                "Branch",
                "Culture",
                "Fruit",
                "Grass",
                "Oak",
                "Picea",
                "Science",
                "Shrub",
                "Wood"
            ],
            "type": "string"
        }
    },
    "properties": {
        "Branch": {
            "$ref": "#/definitions/ResourceData"
        },
        "Culture": {
            "$ref": "#/definitions/ResourceData"
        },
        "Fruit": {
            "$ref": "#/definitions/ResourceData"
        },
        "Grass": {
            "$ref": "#/definitions/ResourceData"
        },
        "Oak": {
            "$ref": "#/definitions/ResourceData"
        },
        "Picea": {
            "$ref": "#/definitions/ResourceData"
        },
        "Science": {
            "$ref": "#/definitions/ResourceData"
        },
        "Shrub": {
            "$ref": "#/definitions/ResourceData"
        },
        "Wood": {
            "$ref": "#/definitions/ResourceData"
        }
    },
    "type": "object"
}

=== betairylia/Titanians/dist/data/resources.json
{
    "$schema": "resources-schema.json",
    "Grass": {
        "env": true,
        "regenFactor": 0.0002
    },
    "Shrub": {
        "env": true,
        "regenFactor": 0.00013
    },
    "Oak": {
        "env": true,
        "regenFactor": 0.00008
    },
    "Picea": {
        "env": true,
        "regenFactor": 0.000005
    },
    "Fruit": {
        "initialMaxStacks": 1000,
        "initialUTransferSpeed": 0.05
    },
    "Wood": {
        "initialMaxStacks": 20
    },
    "Branch": {
        "initialMaxStacks": 100
    },
    "Culture": {
        "initialMaxStacks": 5000
    }
}
